@startuml



class Book {
}

class BookController {

}

class BookServiceImpl {
}

class User {}
class UserController {}
class UserServiceImpl {}

class Loan {}



BookController - BookServiceImpl
BookController -- Book

User -- Book
User - Loan
UserController - UserServiceImpl








@enduml
